In [1]:
import pandas as pd
import numpy as np
#Load common functions
# %run common.ipynb
import ipynb.fs.full.common as common
pd.set_option('display.max_columns', None)

# data_comparison_GNPxC_LCU_Conversions
## NOTA IMPORTANTE:
- MML habla de GNP (Gross National Product) == PNB (Producto Bruto Nacional)

Sin embargo, no encontramos existencia de datos de GNP año a año desde 1960 hasta al menos 2000, país por país, para todos los países.
Consultado con Igal, corroboró que no se suele trabajar con GNP.

- El set de datos a comparar entonces es GDP (Gross Domestic Product) == PIB (Producto Interno Bruto)

- La comparación no es directa. Sin embargo, podemos asumir que la diferencia entre GNP y GDP de cada pais es NO significativa.

Más aún, si llegarámos a encontrar algun dataset de GNP de algún país en algun periodo, podriamos efectivamente compararlos. Tal vez, teniendo un candidato de país importante por región alcance (uno de LAM, uno de DEVELOPED, etc)

Otro punto a tener en cuenta es la unidad de medida.
- MML midio GNP a valor USD de 1960
- Notas de Igal: https://es.overleaf.com/9742826469tmfsvjwrxktq

Vamos a intentar reproducir el cambio de base como evidencia de la posibilidad, para un pais en particular.

In [2]:
MML_VARIABLE_ANALYZED = 'GNPXC'
REGION = 'ASIA' 
COUNTRY_COL_NAME = 'country'

In [3]:
df_lcu_current = pd.read_excel(f"data/{REGION}/GDP Current LCU.xlsx", sheet_name='ny_gdp_pcap_cn')
df_lcu_constant = pd.read_excel(f"data/{REGION}/GDP Constant LCU.xlsx", sheet_name='ny_gdp_pcap_kn')
df_lcu_current.columns = df_lcu_current.columns.astype(str)
df_lcu_constant.columns = df_lcu_constant.columns.astype(str)

In [4]:
df_lcu_current[0:10]

,country,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.6k,14.1k,17.5k,20.4k,22k,24.2k,25.1k,26.7k,29.1k,29.4k,29.7k,32.1k,34.1k,34.6k,36.9k,37k,36.6k,37.3k,40.4k,41.7k,43k,46.2k,48.5k,44.1k,42.1k,44.7k,44.2k,47.3k,48.1k,50.8k,50.9k,52.5k,54.2k,NaN,NaN
1,Afghanistan,2690,2690,2630,3540,3690,4550,6190,7240,5810,5820,7040,7180,6090,6440,7810,8390,8890,10.1k,11.1k,12k,12k,13.1k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8060,9350,10.1k,12k,13.2k,17.9k,18.6k,21.5k,24.9k,28.2k,33k,35.3k,35.3k,35.5k,34.6k,35.4k,35.7k,38.6k,39.7k
2,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20µ,20µ,20µ,20µ,20µ,20µ,20µ,20µ,20µ,30µ,30µ,60µ,0.0003,0.00225,0.0502,1.08,58,118,166,1080,5590,11.6k,38k,73.3k,105k,166k,209k,239k,306k,248k,330k,434k,487k,507k,532k,500k,574k,680k,832k,1.03M,1.03M
3,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5610,5690,5740,5680,5490,5490,5550,5400,5220,5580,4940,4850,15.1k,37.5k,55.5k,69.6k,106k,105k,123k,143k,162k,184k,200k,223k,244k,267k,292k,325k,367k,391k,426k,448k,460k,466k,483k,498k,512k,540k,571k,593k,570k
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1360,1460,1630,1870,2190,2470,2880,3540,4210,4770,5330,5760,6350,6920,7470,7950,8720,9360,10k,10.8k,11.6k,12.2k,12.6k,12.6k,13.1k,13.8k,14.5k,16.2k,17k,18.1k,23.7k,25.7k,26.6k,28.6k,30.6k,32.2k,34k,34.9k,33.3k,31.3k,30.8k,31.1k,30.1k,29.8k,31.1k,32.2k,33.9k,34.5k,35.4k,36.5k,32.5k
5,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106k,119k,132k,110k,128k,159k,165k,147k,128k,119k,109k,86.2k,87.1k,81.8k,88.2k,102k,97.7k,97k,94k,94.9k,99.9k,106k,108k,98.8k,105k,122k,115k,116k,123k,133k,145k,154k,154k,163k,118k,124k,144k,150k,156k,161k,142k,140k,149k,161k,157k,133k
6,Argentina,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10µ,30µ,70µ,0.00014,0.00026,0.00076,0.00374,0.0266,0.176,0.325,0.748,3.51,101,2110,5470,6760,6960,7480,7410,7720,8210,8290,7770,7710,7210,8300,9870,12.6k,15k,18.2k,22.6k,28.7k,30.8k,40.7k,52.8k,63.2k,79.3k,107k,138k,189k,242k,331k,485k,606k
7,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.2,22.7,90.1,1250,57k,162k,209k,257k,307k,320k,336k,385k,449k,538k,636k,752k,898k,1.07M,1.23M,1.09M,1.2M,1.31M,1.48M,1.57M,1.66M,1.72M,1.73M,1.89M,2.04M,2.21M,2.09M
8,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8670,8810,8530,8400,8340,8870,9740,11.9k,10.2k,10.2k,11.5k,11.5k,11.5k,12.1k,12k,11k,11.5k,11.7k,12.8k
9,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3370,3820,4750,5740,6460,7180,7960,9110,10.5k,12.7k,14.8k,17.4k,19.1k,19.8k,20.5k,20.9k,22k,23.7k,22.7k,24.4k,25.6k,26.8k,27.7k,29.4k,28k,28.1k,29.2k,30.9k,33.9k,37.8k,42.2k,43.3k,38.2k,35.2k,34.4k,35.8k,34.9k,36.5k,38.6k,41k,41.5k,45k,46.9k,37.8k

In [5]:
#CHEQUEAR EXISTENCIA DE NANS en LAM
#ES OBVIO QUE EL DATASET ESTA INCOMPLETO, PERO CON SUERTE TENEMOS UNA REGION COMPLETA??

In [6]:
def fix_countries_for_region(df, region=REGION):
    '''Match country column name in dataset with MML dict of country names for region.
    Unfortunately, it's a manual job. We know which names are missing according to MML, but we don't how the truth dataset named that country (if exists at all).
    
    '''
    if region == 'DEVELOPED':
        fix_countries_for_developed(df)
    if region == 'LAM':
        fix_countries_for_lam(df)
    if region == 'AFRICA':
        fix_countries_for_africa(df)
    if region == 'ASIA':
        fix_countries_for_asia(df)
def fix_countries_for_lam(df):
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Brazil', 'Brasil')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Trinidad and Tobago', 'Trinidad y Tobago')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Dominican Republic', 'Republica Dominicana')
def fix_countries_for_developed(df):
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Ukraine', 'Ucrania')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Bosnia and Herzegovina','Bosnia y Herzegovina')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Kyrgyz Republic','Kirguistan')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Germany','Alemania')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'France','Francia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Macedonia, FYR','Macedonia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Slovenia','Eslovenia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Slovak Republic','Eslovaquia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Switzerland','Suiza')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Denmark','Dinamarca')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'United Kingdom','Reino Unido')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'New Zealand','Nueva Zelanda')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Spain','España')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Poland','Polonia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Ireland','Irlanda')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Romania','Rumania')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Finland','Finlandia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Moldova','Moldavia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Sweden','Suecia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Kazakhstan','Kazajistan')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Russia','Rusia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Latvia','Letonia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Norway','Noruega')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Lebanon','Libano')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Czech Republic','Republica Checa')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Hungary','Hungria')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Azerbaijan','Azerbaiyan')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Japan','Japon')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'United States','EEUU')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Greece','Grecia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Italy','Italia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Belgium','Belgica')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Belarus','Bielorrusia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Tajikistan','Tayikistan')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Croatia','Croacia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Lithuania','Lituania')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'Netherlands','Paises Bajos')
    common.replace_value_in_column(df,COUNTRY_COL_NAME,'North Macedonia','Macedonia')
def fix_countries_for_africa(df):
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Morocco', 'Marruecos')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Sierra Leone', 'Sierra Leona')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Algeria', 'Argelia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Kenya', 'Kenia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Egypt', 'Egipto')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Tunisia', 'Tunez')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Libya', 'Libia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Zimbabwe', 'Rhodesia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Congo, Dem. Rep.', 'Zaire')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Congo, Rep.', 'Congo')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Cameroon', 'Camerun')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Ethiopia', 'Etiopia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, "Cote d'Ivoire", 'Costa de Marfil')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Central African Republic', 'Centroafrica')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'United Republic of Tanzania', 'Tanzania')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'South Africa', 'Sudafrica')
def fix_countries_for_asia(df):
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Thailand', 'Tailandia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Papua New Guinea', 'Nueva Guinea')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Iraq', 'Irak')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Philippines', 'Filipinas')
    # common.replace_value_in_column(df,COUNTRY_COL_NAME, 'China, Taiwan Province of China', 'Taiwan')
    # common.replace_value_in_column(df,COUNTRY_COL_NAME, "Dem. People's Republic of Korea", 'Corea del Norte')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'South Korea', 'Corea del Sur')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Syria', 'Siria')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Iran (Islamic Republic of)', 'Iran')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Malaysia', 'Malasia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Myanmar', 'Birmania')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Jordan', 'Jordania')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Singapore', 'Singapur')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Hong Kong, China', 'Hong Kong')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Viet Nam', 'Vietnam')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Cambodia', 'Camboya')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Turkey', 'Turquia')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Afghanistan', 'Afganistan')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, "Lao", 'Laos')
    common.replace_value_in_column(df,COUNTRY_COL_NAME, 'Saudi Arabia', 'Arabia Saudita')

In [7]:
print(f"Missing countries for region {REGION}")
missing_countries = common.get_missing_countries_for_region(df_lcu_current, COUNTRY_COL_NAME, REGION)
print(missing_countries)
fix_countries_for_region(df_lcu_current)
missing_countries = common.get_missing_countries_for_region(df_lcu_current, COUNTRY_COL_NAME, REGION)
print("Missing countries for region after fix")
print(missing_countries)
print(f"Missing countries for region {REGION}")
missing_countries = common.get_missing_countries_for_region(df_lcu_constant, COUNTRY_COL_NAME, REGION)
print(missing_countries)
fix_countries_for_region(df_lcu_constant)
missing_countries = common.get_missing_countries_for_region(df_lcu_constant, COUNTRY_COL_NAME, REGION)
print("Missing countries for region after fix")
print(missing_countries)

Missing countries for region ASIA
{'Tailandia', 'Afganistan', 'Singapur', 'Camboya', 'Arabia Saudita', 'Nueva Guinea', 'Corea del Sur', 'Irak', 'Birmania', 'Hong Kong', 'Taiwan', 'Malasia', 'Jordania', 'Siria', 'Turquia', 'Corea del Norte', 'Laos', 'Filipinas'}
Missing countries for region after fix
{'Taiwan', 'Corea del Norte'}
Missing countries for region ASIA
{'Tailandia', 'Afganistan', 'Singapur', 'Camboya', 'Arabia Saudita', 'Nueva Guinea', 'Corea del Sur', 'Irak', 'Birmania', 'Hong Kong', 'Taiwan', 'Malasia', 'Jordania', 'Siria', 'Turquia', 'Corea del Norte', 'Laos', 'Filipinas'}
Missing countries for region after fix
{'Taiwan', 'Corea del Norte'}

In [8]:
#Filter countries for region
df_lcu_current = common.get_countries_for_region(df_lcu_current, COUNTRY_COL_NAME, REGION)
df_lcu_constant = common.get_countries_for_region(df_lcu_constant, COUNTRY_COL_NAME, REGION)
years_filtered = np.arange(1960,2001,1)
columns_filter = np.append([COUNTRY_COL_NAME],years_filtered)

#Filter years of interest
df_lcu_current = df_lcu_current[columns_filter]
df_lcu_constant = df_lcu_constant[columns_filter]

In [9]:
assert 0 == df_lcu_current.isna().sum().sum(), "MISSING VALUES FOR LCU CURRENT GDP" #If 0, then we don't have missing values.
assert not (df_lcu_current == 0).any().any(), "CELLS WITH 0 FOR LCU CURRENT GDP"

AssertionError: MISSING VALUES FOR LCU CURRENT GDP

In [10]:
assert 0 == df_lcu_constant.isna().sum().sum(), "MISSING VALUES FOR LCU CONSTANT GDP" #If 0, then we don't have missing values.
assert not (df_lcu_constant == 0).any().any(), "CELLS WITH 0 FOR LCU CONSTANT GDP"

AssertionError: MISSING VALUES FOR LCU CONSTANT GDP

df_lcu_current = df_lcu_current[df_lcu_current[COUNTRY_COL_NAME] == 'Argentina']
df_lcu_constant = df_lcu_constant[df_lcu_constant[COUNTRY_COL_NAME] == 'Argentina']

In [11]:
display(df_lcu_current)
display(df_lcu_constant)

,country,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
1,Afganistan,2690,2630,3540,3690,4550,6190,7240,5810,5820,7040,7180,6090,6440,7810,8390,8890,10.1k,11.1k,12k,12k,13.1k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Bangladesh,468,481,489,481,512,541,590,590,649,672,641,566,930,1450,2460,2100,2030,2660,3060,3530,4050,4420,4860,5350,6380,7010,7870,8450,9180,10.1k,10.5k,11.1k,11.4k,12k,13.2k,16.1k,17.1k,18.5k,19.7k,21k,22.4k
36,China,187,175,183,210,242,257,238,225,246,279,292,296,313,314,332,321,344,385,423,468,497,533,588,702,866,973,1120,1380,1540,1660,1910,2330,3030,4080,5090,5900,6480,6860,7230,7940,8720
81,Hong Kong,2350,2630,3050,3390,3880,3930,4160,4350,5030,5840,6600,7810,9740,10.8k,11.1k,14k,16k,18.4k,22.9k,28.4k,33.5k,37.2k,40.7k,48.5k,51k,58k,70.7k,82.8k,94.4k,105k,120k,139k,158k,174k,182k,192k,212k,200k,195k,201k,197k
86,Indonesia,5220,14.4k,33.8k,73.1k,236k,3070,8010,19.3k,24.3k,29.1k,31.2k,37.7k,54.4k,84k,96.7k,115k,138k,162k,222k,308k,358k,386k,466k,539k,574k,609k,727k,812k,938k,1.08M,1.23M,1.38M,1.73M,1.97M,2.31M,2.66M,3.09M,4.65M,5.27M,6.57M,7.68M
87,India,406,428,482,550,568,630,723,749,807,843,883,951,1130,1300,1370,1440,1590,1690,1810,2100,2420,2640,3000,3290,3630,3970,4410,5130,5770,6600,7430,8370,9450,10.9k,12.5k,14.2k,15.4k,17.4k,19.2k,20.3k,21.5k
89,Iran,14.9k,15.4k,15.8k,16.8k,18.8k,20.1k,21.7k,24.2k,26.6k,29.2k,35.5k,43.2k,60.4k,98.3k,108k,142k,163k,153k,171k,175k,200k,254k,313k,328k,334k,325k,379k,413k,497k,674k,932k,1.22M,1.78M,2.31M,3.21M,4.34M,5.02M,5.53M,7.33M,9.57M,11.1M
90,Irak,87.5,91,89.6,103,NaN,NaN,NaN,112,112,118,133,129,142,301,340,434,470,546,842,1160,808,881,852,958,965,921,1080,1170,1200,3210,2370,6250,17k,84.9k,332k,313k,704k,774k,1.51M,2.14M,1.71M
95,Jordania,NaN,NaN,NaN,NaN,183,185,164,134,154,133,134,149,159,192,211,267,317,355,427,490,588,644,669,686,679,743,730,721,713,774,787,908,924,988,1030,1040,1060,1130,1150,1170,1220
100,Camboya,3830,3830,4120,4330,4700,4860,5040,5500,6060,5700,9730,11.3k,23.1k,62.8k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,683k,689k,791k,838k,898k,1.01M,1.13M,1.16M,1.26M
103,Corea del Sur,11.7k,13.8k,19k,26.4k,29k,36.2k,43.6k,54.9k,70.1k,86.7k,105k,127k,162k,228k,299k,404k,511k,680k,863k,1.04M,1.28M,1.46M,1.71M,1.95M,2.16M,2.5M,2.92M,3.47M,3.91M,4.68M,5.6M,6.34M,7.13M,8.34M,9.69M,10.8M,11.8M,11.6M,12.7M,13.9M,14.9M
106,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.1k,28.9k,44.5k,48.8k,58.4k,101k,144k,165k,179k,206k,234k,293k,349k,436k,821k,1.97M,2.56M,2.9M
112,Sri Lanka,680,673,697,718,728,733,775,898,957,1090,1100,1170,1390,1760,1930,2160,2550,2940,3540,4420,5570,6400,7730,9640,10k,10.9k,11.8k,13.2k,14.7k,18.6k,21.2k,24k,27.9k,32k,36.6k,41.8k,48.2k,54.8k,59.3k,67k,74.4k
129,Birmania,278,281,302,300,297,305,309,337,361,370,371,371,385,519,700,813,891,938,1000,1080,1160,1250,1320,1390,1440,1490,1620,1810,2470,3350,4040,5140,7110,9600,12.3k,15.7k,21.2k,29.9k,41.1k,50.8k,64.6k
131,Mongolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3730,4000,4310,4490,4490,4550,4400,4460,4600,5010,5860,10.2k,25k,101k,168k,283k,319k,399k,401k,455k,511k,575k
137,Malasia,692,705,856,885,950,983,972,990,1060,1090,1170,1260,1620,1930,1840,2250,2530,2890,3450,3860,4080,4330,4750,5240,4970,4460,4910,5430,6000,6600,7300,7930,8840,9780,10.9k,12.1k,13.1k,12.8k,13.3k,15.4k,14.9k
146,Nepal,395,419,435,466,511,618,564,618,675,726,725,824,776,975,1230,1270,1230,1380,1510,1560,1780,1970,2100,2390,2760,3230,3620,4270,4840,5470,6380,7660,8570,9470,10.2k,11.3k,12.4k,13k,14.5k,15.9k,18.1k
150,Pakistan,426,435,456,499,555,598,662,695,731,821,850,891,1070,1360,1660,1890,2110,2410,2580,3000,3450,3890,4220,4710,5120,5400,5820,6660,7370,7950,9210,10.6k,11.5k,13.1k,15.1k,16.6k,18.5k,19.9k,21.2k,29.8k,31.7k
153,Filipinas,608,658,742,777,824,880,918,996,1070,1250,1460,1600,1980,2640,2960,3400,3780,4230,5000,5840,6570,7210,8160,11.3k,12k,12.4k,13.6k,15.5k,17.5k,19.8k,22.4k,23.7k,25.3k,28.3k,31.2k,34.8k,38k,40.8k,43.9k,47.4k,50.5k
155,Nueva Guinea,95.2,99.6,103,112,124,137,152,163,181,207,222,246,306,334,330,372,393,408,469,478,458,464,553,577,594,614,665,721,676,666,763,873,983,1090,1190,1280,1300,1400,1540,1660,1740
166,Arabia Saudita,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500,3600,4150,5280,6270,8250,22.9k,22.2k,29k,31.9k,31.6k,41.1k,56.5k,60.5k,47.8k,38.1k,33.9k,28.7k,23.3k,22.2k,21.9k,22.8k,27.1k,29.5k,29.7k,28k,27.8k,28.8k,31.2k,32k,27.8k,30k,34.4k,32.6k
169,Singapur,1370,1450,1560,1490,1580,1740,1920,2170,2490,2830,3280,3860,4740,5750,6070,6540,7030,7790,8870,10.7k,12k,12.8k,14.2k,15.3k,14.9k,15k,16.4k,18.8k,20.9k,23.1k,25.1k,26.3k,29.6k,32.9k,35.3k,37k,39.2k,36.5k,36.9k,41.1k,38.9k
185,Siria,717,841,911,984,945,909,961,1010,1120,1070,1220,1360,1400,2180,2730,3170,3350,3890,4520,5740,7110,7170,7370,7320,7820,9080,11.2k,15.9k,17.3k,21.6k,24.3k,28.2k,30.5k,36.3k,39.8k,46.8k,49.1k,50.7k,51.1k,55.1k,58.1k
189,Tailandia,2260,2380,2460,2620,2870,3350,3470,3640,3890,4000,4040,4350,5530,6770,7170,7990,9090,10.8k,12k,14k,15.7k,17.1k,18.4k,19.3k,20.3k,21.4k,24.1k,28.4k,33.3k,38.6k,43.8k,49k,55.9k,62.7k,70.9k,77.1k,77.4k,76.3k,76.9k,80.5k,84.1k
196,Turquia,0.00255,0.00279,0.00316,0.00333,0.00348,0.004,0.00434,0.00474,0.00514,0.00563,0.00679,0.0079,0.00971,0.0129,0.0164,0.0205,0.0257,0.0376,0.0646,0.119,0.176,0.228,0.295,0.457,0.714,1.02,1.46,2.48,4.29,7.29,11.5,19.6,35,67.2,133,249,478,1170,1720,2710,3850
207,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1920,9620,45.1k,237k,422k,617k,1.1M,1.56M,1.94M,2.42M,3.06M,3.58M,4.07M,4.62M,5.06M,5.53M,5.96M
210,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6k,14.3k,16.7k,19.1k,23.5k,34.8k,47.9k,55.3k,52.2k,70.3k,89.7k,92.8k

,country,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
1,Afganistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Bangladesh,20.2k,20.7k,20.1k,21.6k,21.3k,21.2k,20.1k,21.4k,21k,21.7k,20.1k,17k,17.3k,18.6k,17.5k,18.1k,18.1k,18.9k,19.3k,18.9k,19.8k,19.7k,19.9k,20.3k,20.5k,20.8k,21k,20.9k,21k,21.7k,21.9k,22.6k,23.1k,23.5k,24.2k,24.8k,25.3k,26.1k,26.8k,27.6k,28.5k
36,China,1090,1020,1100,1270,1450,1560,1430,1340,1520,1770,1840,1860,1960,1970,2100,2040,2160,2370,2520,2680,2780,2990,3270,3710,4150,4460,4900,5360,5500,5640,6070,6850,7720,8620,9470,10.3k,11.1k,11.9k,12.7k,13.7k,14.7k
80,Hong Kong,33.9k,37.2k,41.6k,44.1k,49.2k,49.7k,49.2k,49.8k,54.6k,58.2k,61.1k,66.3k,72.3k,71.8k,70.8k,81.2k,89.4k,95.1k,100k,108k,115k,116k,122k,132k,132k,145k,162k,175k,177k,183k,192k,202k,211k,219k,220k,219k,228k,213k,216k,231k,231k
85,Indonesia,6.46M,6.41M,6.1M,6.15M,6.05M,6.05M,5.97M,6.45M,6.7M,7.02M,7.32M,7.63M,8.03M,8.43M,8.63M,9M,9.55M,9.95M,10.4M,11.2M,11.8M,11.8M,12M,12.6M,12.6M,13.1M,13.5M,14M,14.7M,15.5M,16.3M,17.1M,17.9M,18.9M,20.2M,21.4M,22.1M,18.9M,18.8M,19.5M,19.9M
86,India,16.6k,16.8k,17.4k,18.3k,17.5k,17.1k,18.1k,18.3k,19.1k,19.6k,19.5k,18.9k,19.1k,18.9k,20.2k,20k,21k,21.7k,20.1k,21k,21.7k,21.9k,23k,23.3k,24k,24.6k,25k,26.9k,27.9k,28.8k,28.5k,29.5k,30.3k,31.7k,33.4k,35.3k,36k,37.5k,40.1k,41k,42.2k
88,Iran,41.2M,43.6M,45.5M,48.4M,55.3M,59.9M,65.1M,72.8M,82.4M,89.2M,99.3M,111M,117M,121M,115M,131M,122M,101M,87.5M,61.3M,55.9M,68.1M,71M,62.2M,61M,52.6M,51M,46.5M,47.7M,52.8M,58M,58.6M,58.2M,56.5M,57M,59.2M,58.7M,59.2M,59M,61.6M,61.4M
89,Irak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.39M,1.39M,1.4M,1.43M,1.44M,1.45M,1.63M,1.78M,2.02M,1.99M,2.26M,2.65M,3.21M,3.09M,3.11M,2.64M,2.53M,2.51M,2.57M,2.75M,2.69M,2.55M,3.92M,1.37M,1.77M,2.24M,2.25M,2.23M,2.4M,2.82M,3.69M,4.21M,4.78M,4.72M
94,Jordania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1940,2050,2290,2690,2890,3270,3370,3160,3160,2950,2990,2950,2880,2460,2340,2260,2440,2410,2410,2460,2440,2460,2480,2520,2580,2670
99,Camboya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.38M,869k,925k,950k,960k,979k,1.08M,1.16M,1.23M
102,Corea del Sur,1.21M,1.22M,1.29M,1.38M,1.44M,1.57M,1.68M,1.85M,2.08M,2.24M,2.42M,2.55M,2.88M,3.1M,3.29M,3.66M,4.05M,4.43M,4.74M,4.59M,4.84M,5.17M,5.77M,6.3M,6.73M,7.42M,8.28M,9.18M,9.74M,10.6M,11.6M,12.2M,12.9M,14M,15.2M,16.2M,17M,16.1M,17.8M,19.2M,20M
105,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.15M,4.24M,4.32M,4.14M,3.94M,4.37M,4.53M,4.6M,4.72M,4.87M,5.14M,5.38M,5.63M,5.9M,6.02M,6.34M,6.6M,6.87M
111,Sri Lanka,66.2k,67.2k,67.3k,68.3k,68.4k,70.1k,72.8k,75.3k,79.2k,80.5k,79.9k,78k,81.9k,83.5k,87k,88.2k,91k,94.4k,98.8k,103k,107k,110k,113k,118k,122k,125k,126k,127k,128k,135k,139k,143k,152k,159k,166k,171k,181k,189k,196k,206k,202k
127,Birmania,155k,155k,165k,166k,166k,166k,154k,154k,162k,165k,168k,170k,167k,167k,171k,175k,182k,189k,196k,204k,214k,222k,228k,234k,238k,236k,226k,205k,193k,196k,196k,202k,215k,227k,241k,254k,266k,277k,297k,330k,367k
129,Mongolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.82M,2.98M,3.08M,3.18M,3.27M,3.48M,3.5M,3.58M,3.64M,3.45M,3.1M,2.78M,2.67M,2.71M,2.86M,2.9M,2.99M,3.06M,3.13M,3.14M,3.2M
135,Malasia,5030,5180,5390,5510,5760,6040,6120,6440,6600,6830,7340,7840,8550,9050,8900,9690,10.2k,10.6k,11.3k,11.8k,12.3k,12.8k,13.2k,13.9k,13.4k,13.2k,13.5k,14.4k,15.3k,16.2k,17.2k,18.3k,19.6k,20.9k,22.4k,24k,25.1k,22.7k,23.5k,25k,24.6k
144,Nepal,25.2k,25.3k,25.3k,26.8k,26k,27.3k,26.4k,26.1k,26.7k,26.9k,26k,26.3k,25.6k,26.6k,26.4k,27k,27.2k,27.8k,27.8k,26.5k,28.1k,28.5k,27k,28.9k,30k,30.7k,30.5k,32.1k,32.8k,33.4k,34.7k,35.1k,35.5k,37.4k,37.7k,38.8k,39.9k,40.3k,41.2k,43k,44.3k
148,Pakistan,16.2k,16.5k,17.5k,18.3k,19.7k,20.3k,20.9k,21.8k,22.4k,24.3k,23.7k,23.3k,24.2k,24.4k,24.7k,25.2k,25.4k,26.6k,26.8k,28.5k,29.8k,30.7k,31.7k,32.2k,33.5k,34.3k,35.3k,36.9k,37.5k,38.1k,38.9k,40.7k,40.3k,40.7k,41.5k,42.3k,41.5k,41.4k,41.7k,42.4k,42.8k
151,Filipinas,59.7k,60.5k,62.7k,62.8k,64.1k,64.9k,66.3k,67.7k,68.8k,69.3k,71k,72.7k,76.9k,77.3k,79.2k,83.8k,86.1k,88.1k,90.5k,92.7k,93.3k,94.1k,93.3k,84.4k,76.5k,77.1k,78.3k,81.4k,84.2k,84.7k,82.2k,80.6k,80.4k,81.9k,83.8k,86.7k,89.1k,86.7k,87.7k,89.6k,90.3k
153,Nueva Guinea,3220,3360,3430,3650,3940,4080,4150,4240,4480,4850,5040,5200,5410,5410,5240,4930,4850,5130,5090,4840,4700,4590,4610,4480,4540,4630,4640,4660,4480,4250,4540,5050,5840,6040,5710,6000,5630,5280,5250,5010,4900
164,Arabia Saudita,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.4k,54.5k,83k,95.7k,112k,133k,147k,127k,142k,145k,130k,138k,138k,132k,98.1k,77.3k,69.5k,59.3k,66k,58.9k,63.8k,61.1k,67.9k,75.6k,76.3k,73.2k,71.8k,70.3k,70.7k,70.1k,70.7k,66.7k,68.8k,66.3k
167,Singapur,5190,5430,5830,5500,5790,6220,6850,7640,8570,9610,10.6k,11.8k,12.8k,13.4k,13.7k,14.5k,15.3k,16.3k,17.6k,19.2k,20.2k,20.8k,22.2k,23.7k,23.6k,23.9k,26.1k,28.3k,30.3k,32k,33.2k,34.3k,37.3k,40.1k,41.7k,43.1k,45.1k,42.7k,44.7k,47.9k,46.2k
183,Siria,24.7k,29.8k,26.4k,27.9k,27.6k,24.7k,25.8k,25.9k,29.8k,28.3k,29.7k,36.1k,31.2k,38k,42.7k,46.4k,44k,46.8k,45.6k,50.5k,52.5k,52k,51.4k,45.8k,48.5k,43.2k,42.5k,48.6k,40.7k,41k,42.9k,47.1k,48.6k,50.7k,52.7k,56.3k,57.5k,59.7k,56.1k,55.1k,54.5k
187,Tailandia,14.1k,14.7k,15.4k,16k,16.8k,18.1k,19.1k,20k,20.7k,22.4k,22.9k,23.2k,24.8k,25.3k,25.8k,27.6k,29.6k,31.9k,32.9k,33.9k,35.2k,36.4k,37.7k,39.1k,40.2k,41.7k,44.8k,49.9k,55.1k,60.4k,64.8k,69.4k,74.4k,79.6k,85.2k,89.1k,85.6k,78.1k,80.7k,83.5k,85.5k
194,Turquia,4400,4540,4830,4970,4990,5420,5550,5790,5880,5930,6110,6410,6460,6660,6980,7530,7610,7560,7340,7000,7180,7270,7460,7790,7950,8340,8950,8990,8860,9510,9420,9730,10.3k,9680,10.3k,10.9k,11.5k,11.6k,11k,11.6k,10.8k
205,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.03M,7.13M,7.16M,7.26M,7.46M,7.84M,8.06M,8.37M,8.91M,9.44M,10.1M,10.9M,11.7M,12.5M,13M,13.5M,14.2M,15M
208,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6k,12.8k,13.1k,13k,13.2k,13.4k,13.5k,13.8k,14.2k,14.3k,14.7k,14.9k

df_lcu = pd.concat([df_lcu_current, df_lcu_constant], axis=0)
df_lcu = df_lcu.rename({COUNTRY_COL_NAME: 'Type'}, axis=1).reset_index(drop=True)
df_lcu.at[0,'Type'] = 'current'
df_lcu.at[1,'Type'] = 'constant'
display(df_lcu)